//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFileUpload
{


    public partial class About
    {
    }
}

// This file is clone from rqmesh111291 repo anf pufpufe of fhis file is just checking cmnt 6
